### Creates a new member entity
POST http://localhost:4000/members
Content-Type: application/json


{
  "firstName": "Razin",
  "lastName": "Prakesh",
  "email": "razin@example.com",
  "phoneNumber": "96734627",
  "address": "123 Orchard Road",
  "dateOfBirth": "2000-05-26",
  "membershipStartDate": "2025-09-25",
  "status": "ACTIVE"
}

###